# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ikbis}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Moski Doski"]
  s.date = %q{2010-01-14}
  s.default_executable = %q{ikbis-auth}
  s.description = %q{This gem implements a full-featured ruby interface for the Ikbis API.}
  s.email = %q{abushaikh@gmail.com}
  s.executables = ["ikbis-auth"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "bin/ikbis-auth",
     "lib/ikbis.rb",
     "lib/ikbis/advanced.rb",
     "lib/ikbis/advanced/base.rb",
     "lib/ikbis/advanced/media.rb",
     "lib/ikbis/advanced/photo.rb",
     "lib/ikbis/advanced/test.rb",
     "lib/ikbis/advanced/upload.rb",
     "lib/ikbis/advanced/video.rb",
     "lib/ikbis/simple.rb",
     "lib/ikbis/simple/base.rb",
     "lib/ikbis/simple/channel.rb",
     "lib/ikbis/simple/photo.rb",
     "lib/ikbis/simple/user.rb",
     "lib/ikbis/simple/video.rb",
     "test/ikbis_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/moski/ikbis}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This gem implements a full-featured ruby interface for the Ikbis API.}
  s.test_files = [
    "test/ikbis_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<multipart-post>, [">= 1.0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<oauth>, [">= 0.3.6"])
    else
      s.add_dependency(%q<multipart-post>, [">= 1.0"])
      s.add_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_dependency(%q<oauth>, [">= 0.3.6"])
    end
  else
    s.add_dependency(%q<multipart-post>, [">= 1.0"])
    s.add_dependency(%q<httparty>, [">= 0.5.0"])
    s.add_dependency(%q<oauth>, [">= 0.3.6"])
  end
end
